# Generated by Django 3.2.8 on 2021-10-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('red', 'Do it now'), ('orange', 'Must do today'), ('yellow', 'Do it anyway'), ('blue', 'Do it'), ('green', 'Just do it')], default='green', max_length=11)),
            ],
        ),
    ]
